#!/bin/sh
#
# This script builds Varnish Cache in chroot from a tarball.
#
# Author: Lasse Karstensen <lkarsten@varnish-software.com>, March 2015.
# Author: Dridi Boukelmoune <dridi.boukelmoune@gmail.com>, March 2018.

set -e
set -u

ELVER=${ELVER:-el7}
CHROOT="epel-${ELVER#el}-x86_64"

rm -rf build
mkdir -p build
cd build

SOURCE=$(ls -1 ../sources/varnish-*.tar.gz 2>/dev/null || ls -1 ../sources/varnish-*.tgz 2>/dev/null)

tar xf "$SOURCE"

VERSION=$(./varnish-*/configure --version | awk 'NR == 1 {print $3}')
MAJOR=${VERSION%.*}
MINOR=${VERSION##*.}
MINOR=${MINOR%%-*}
RELEASE=${VERSION#*-}

cp -r -L ../redhat/* .

ln "$SOURCE" `basename "$SOURCE"`

if [ -n "${WEEKLY_VERSION:-}" ]; then
    sed -i -e "s/^Version:.*/Version: $WEEKLY_VERSION/" ./*.spec
    sed -i -e "s/.*define v_rc.*/\%define v_rc 0/" ./*.spec
else
    sed -i -e "s/^Version:.*/Version: $MAJOR.$MINOR/" ./*.spec
    sed -i -e "s/.*define v_rc.*/\%define v_rc $RELEASE/" ./*.spec
fi

# while debugging, disable make check since it takes 15-20 minutes to run.
sed -i -e 's/^make check/# make check/' *.spec

mock() {
	command mock --old-chroot \
		--root "$CHROOT" \
		--uniqueext "worker${EXECUTOR_NUMBER:-}" \
		--resultdir "varnish-${MAJOR}/${ELVER}" \
		--define "_smp_mflags -j10" \
		--define "dist .${ELVER}" \
		--define "releasetag ${RPMRELEASE:-1}" \
		"$@"
}

mock --buildsrpm --source . --spec ./*.spec
mock --rebuild "varnish-${MAJOR}/${ELVER}"/varnish*.src.rpm
