#!/bin/bash -x
#
# This script builds Varnish Cache in chroot from a tarball.
#
# Author: Lasse Karstensen <lkarsten@varnish-software.com>, March 2015.
set -o errexit

ELVER=${ELVER:-el7}
CHROOT="epel-${ELVER:2:1}-x86_64"

. common.sh

rm -rf build
mkdir -p build
cd build

SOURCE=$(ls -1 ../sources/varnish-*.tar.gz)
tar xf "$SOURCE"

cp -r ../redhat/* .

ln "$SOURCE" `basename "$SOURCE"`

findversion "$SOURCE"
sed -i -e "s/^Version:.*/Version: $V.$MINOR/" ./*.spec
sed -i -e "s/.*define v_rc.*/\%define v_rc $RELEASE/" ./*.spec

# while debugging, disable make check since it takes 15-20 minutes to run.
sed -i -e 's/^make check/# make check/' *.spec

MOPT="--uniqueext=worker${EXECUTOR_NUMBER} --resultdir=varnish-${V}/${ELVER}"

mock -r "$CHROOT" $MOPT --init
mock -v -r "$CHROOT" $MOPT --buildsrpm \
  -D "_smp_mflags -j10" \
  -D "dist .${ELVER}" \
  --source .\
  --spec ./*.spec

mock -r "$CHROOT" $MOPT --clean
mock -v -r "$CHROOT" $MOPT \
  -D "_smp_mflags -j10" \
  -D "dist .${ELVER}" \
  --rebuild varnish-${V}/${ELVER}/varnish*.src.rpm
