#!/bin/sh

set -e
set -u

WORK_DIR=
VCL_FILE=
WARMUP=
SCRIPT="$0"

usage() {
	cat <<-EOF
	Error: $1.

	Usage: $SCRIPT [-n <workdir>] [-w <warmup>] [<file>]

	Reload and use a VCL on a running Varnish instance. Options must be
	specified in that order when used:

	-n <workdir> : for a different working directory for varnishd
	-w <warmup>  : the waiting period between load and use operations

	When <file> is empty or missing, the active VCL's file is used but
	will fail if the active VCL wasn't loaded from a file.
	EOF
	exit 1
}

varnishadm() {
	if ! OUTPUT=$(command varnishadm -n "$WORK_DIR" -- "$@" 2>&1)
	then
		echo "Command: varnishadm -n '$WORK_DIR' -- $*"
		echo
		echo "$OUTPUT"
		echo
		exit 1
	fi >&2
	echo "$OUTPUT"
}

fail() {
	echo "Error: $*" >&2
	exit 1
}

vcl_count() {
	varnishadm vcl.list |
	awk "BEGIN {n=0} \$NF == \"$1\" {n=n+1} END {print n}"
}

vcl_file() {
	if ! VCL_SHOW="$(varnishadm vcl.show -v "$1")"
	then
		fail "failed to get the VCL file name"
	fi
	echo "$VCL_SHOW" |
	awk 'NR == 1 {print $NF}'
}

vcl_active_name() {
	if ! VCL_LIST="$(varnishadm vcl.list)"
	then
		fail "failed to get the active VCL name"
	fi
	echo "$VCL_LIST" |
	awk '/^active/ {print $NF}'
}

vcl_active_file() {
	set -e

	VCL_NAME=$(vcl_active_name)
	VCL_COUNT=$(vcl_count "$VCL_NAME")

	# XXX: it can happen with a discard but I haven't checked whether it
	#      actually messes with vcl.show (I suspect we don't need this).
	test "$VCL_COUNT" -gt 1 &&
	fail "more than one VCL named $VCL_NAME ($VCL_COUNT)"

	vcl_file "$VCL_NAME"
}

vcl_reload_name() {
	printf "reload_%s" "$(date +%Y%m%dT%H%M%S)"
}

if [ $# -gt 0 ] && [ "$1" = -n ]
then
	test $# -gt 1 || usage "missing argument to -n"
	WORK_DIR="$2"
	shift 2
fi

if [ $# -gt 0 ] && [ "$1" = -w ]
then
	test $# -gt 1 || usage "missing argument to -w"
	WARMUP="$2"
	shift 2
fi

test $# -gt 1 && usage "too many arguments"
test $# -eq 1 && VCL_FILE="$1"

if [ -z "$VCL_FILE" ]
then
	VCL_FILE=$(vcl_active_file)

	case $VCL_FILE in
	/*) ;;
	*) fail "active VCL file not found (got $VCL_FILE)" ;;
	esac
fi

RELOAD_NAME=$(vcl_reload_name)

varnishadm vcl.load "$RELOAD_NAME" "$VCL_FILE"

test -n "$WARMUP" && sleep "$WARMUP"

varnishadm vcl.use  "$RELOAD_NAME"
