#!/bin/bash
#
# reload vcl revisited
# A script that loads new vcl based on data from /etc/sysconfig/varnish
# Ingvar Hagelund <ingvar@redpill-linpro.com>
#
# This is free software, distributed under the standard 2 clause BSD license,
# see the LICENSE file in the Varnish documentation directory
#
# The following environment variables have to be set:
# RELOAD_VCL, VARNISH_VCL_CONF
#
# Requires GNU bash and GNU date
#

debug=false

missing() {
	echo "Missing configuration variable: $1"
	exit 2
}

print_debug() {
	echo "
Parsed configuration:
RELOAD_VCL=\"$RELOAD_VCL\"
VARNISH_VCL_CONF=\"$VARNISH_VCL_CONF\"
"
}

# Fallback to the default configuration
if [ -z "$VARNISH_VCL_CONF" ]; then
	. /etc/sysconfig/varnish
fi

# Get warmup time from defaults or use 0 warmup
WARMUP=${WARMUP_TIME:-0}

$debug && print_debug

# Check configuration
if [ ! "$RELOAD_VCL" = "1" ]; then
	echo "Error: RELOAD_VCL is not set to 1"
	exit 2

elif [ -z "$VARNISH_VCL_CONF" ]; then
	echo "Error: VARNISH_VCL_CONF is not set"
	exit 2

elif [ ! -s "$VARNISH_VCL_CONF" ]; then
	echo "Eror: VCL config $VARNISH_VCL_CONF is unreadable or empty"
	exit 2
fi

# Done parsing, set up command
VARNISHADM="varnishadm"

# Now do the real work
new_config="reload_$(date +%FT%H%M%S)"

# Check if we are able to connect at all
if $VARNISHADM vcl.list > /dev/null; then
	$debug && echo vcl.list succeeded
else
	echo "Unable to run $VARNISHADM vcl.list"
	exit 1
fi

if $VARNISHADM vcl.list | awk ' { print $4 } ' | grep -q $new_config; then
	echo Trying to use new config $new_config, but that is already in use
	exit 2
fi

current_config=$( $VARNISHADM vcl.list | awk ' /^active/ { print $4 } ' )

echo "Loading vcl from $VARNISH_VCL_CONF"
echo "Current running config name is $current_config"
echo "Using new config name $new_config"

if $VARNISHADM vcl.load $new_config $VARNISH_VCL_CONF; then
	$debug && echo "$VARNISHADM vcl.load succeded"
else
	echo "$VARNISHADM vcl.load failed"
	exit 1
fi

# Wait before vcl.use if WARMUP > 0
# Used if backend probes require some time to set backends healthy
sleep $WARMUP

if $VARNISHADM vcl.use $new_config; then
	$debug && echo "$VARNISHADM vcl.use succeded"
else
	echo "$VARNISHADM vcl.use failed"
	exit 1
fi
$VARNISHADM vcl.list
echo Done
exit 0

